/*-------------------------------------------------------------------------
 *
 * fuzz_in.c
 *	  A libFuzzer harness for exercising type "input" (text input)
 *	  functions of PostgreSQL data types, including those provided by
 *	  extensions such as contrib/ltree.
 *
 * An input function has the signature
 *
 *		Datum typinput(cstring str [, Oid typioparam, int32 typmod])
 *
 * and turns the external textual representation of a value into the type's
 * in-memory representation.  The string typically originates from a client,
 * so a buggy input function is a memory-safety hazard: this harness feeds
 * fuzzer-generated bytes (as a NUL-terminated C string) to a chosen input
 * function so that tools such as AddressSanitizer/UndefinedBehaviorSanitizer
 * can catch crashes, buffer overreads and the like.
 *
 * This is the textual-input counterpart of fuzz_recv.c, which fuzzes the
 * binary "receive" functions; the two share the same minimal, no-backend
 * setup and top-level error handling.
 *
 * The concrete function to fuzz is selected at compile time.  The build
 * system defines FUZZ_IN_SYMBOL to the C name of the input function and
 * links the object files that implement it (plus the whole backend, from
 * which the input function resolves its dependencies).  See meson.build and
 * README for the list of ready-made targets and instructions for adding new
 * ones.
 *
 * The harness deliberately keeps the amount of backend state it initializes
 * to a minimum: just enough (memory contexts, error handling and the stack
 * depth reference point) for a self-contained input function to run.  It
 * does *not* start a real backend, so it must only be used with input
 * functions that do not require catalog access or a live transaction.  The
 * ltree/lquery/ltxtquery input functions satisfy this requirement.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  src/test/fuzz/fuzz_in.c
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include "fmgr.h"
#include "miscadmin.h"
#include "utils/memutils.h"

#ifndef FUZZ_IN_SYMBOL
#error "define FUZZ_IN_SYMBOL to the input function to fuzz"
#endif

/*
 * The input function under test.  It is compiled into this binary together
 * with the rest of its module; here we just declare it so we can take its
 * address.  All in-core and contrib input functions have C linkage and the
 * standard PG_FUNCTION_ARGS signature.
 */
extern Datum FUZZ_IN_SYMBOL(FunctionCallInfo fcinfo);

/*
 * libFuzzer entry points.  libFuzzer's runtime provides main(); it calls
 * LLVMFuzzerInitialize() once and LLVMFuzzerTestOneInput() for every test
 * case.  (The backend static library we link against also defines a main(),
 * so the executable is linked with --allow-multiple-definition, which keeps
 * libFuzzer's; see meson.build.)
 */
int			LLVMFuzzerInitialize(int *argc, char ***argv);
int			LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);

/* Long-lived context that owns everything allocated while fuzzing. */
static MemoryContext FuzzContext = NULL;

/*
 * LLVMFuzzerInitialize
 *
 * Called once by libFuzzer before the first test case.  Bring up the minimum
 * backend infrastructure the input functions rely on.
 */
int
LLVMFuzzerInitialize(int *argc, char ***argv)
{
	/*
	 * Establish a reference point for stack-depth checking.  Several parsers
	 * reached from input functions call check_stack_depth(); without a stack
	 * base they would compute a bogus depth.
	 */
	(void) set_stack_base();

	/* Set up the memory context subsystem (TopMemoryContext, ErrorContext). */
	MemoryContextInit();

	/*
	 * A dedicated context for everything a single test case allocates.  We
	 * reset it after every iteration so that memory usage stays bounded even
	 * across millions of inputs.
	 */
	FuzzContext = AllocSetContextCreate(TopMemoryContext,
										"FuzzContext",
										ALLOCSET_DEFAULT_SIZES);
	MemoryContextSwitchTo(FuzzContext);

	return 0;
}

/*
 * LLVMFuzzerTestOneInput
 *
 * Called once per test case with a fuzzer-generated byte string.  The bytes
 * are handed to the input function as a NUL-terminated C string.
 */
int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
	sigjmp_buf	local_sigjmp_buf;
	sigjmp_buf *save_exception_stack = PG_exception_stack;
	ErrorContextCallback *save_context_stack = error_context_stack;

	MemoryContextSwitchTo(FuzzContext);

	/*
	 * Emulate the backend's top-level error handling.  A malformed input is
	 * expected to raise an ordinary ereport(ERROR); we catch it, clean up and
	 * move on to the next test case.  A genuine memory-safety bug will instead
	 * trip a sanitizer or crash, which is exactly what we want the fuzzer to
	 * find.
	 */
	if (sigsetjmp(local_sigjmp_buf, 1) == 0)
	{
		char	   *str;

		PG_exception_stack = &local_sigjmp_buf;

		/*
		 * Input functions expect a NUL-terminated C string.  Make a private,
		 * NUL-terminated copy of the fuzzer input in FuzzContext so the input
		 * function may freely scan it.  An embedded NUL simply terminates the
		 * string early, exactly as it would for a real client value.
		 */
		str = (char *) palloc(size + 1);
		memcpy(str, data, size);
		str[size] = '\0';

		/*
		 * Invoke the input function.  DirectFunctionCall1 supplies the
		 * remaining (unused-by-us) fcinfo fields; typioparam and typmod
		 * default to InvalidOid/-1 which the targeted functions ignore.  The
		 * fcinfo->context left NULL by DirectFunctionCall1 makes soft-error
		 * capable input functions report malformed input as a hard error,
		 * which the handler below catches.
		 */
		(void) DirectFunctionCall1(FUZZ_IN_SYMBOL, CStringGetDatum(str));
	}
	else
	{
		/* Caught an ereport(ERROR): discard the error and continue. */
		PG_exception_stack = save_exception_stack;
		error_context_stack = save_context_stack;
		FlushErrorState();
	}

	PG_exception_stack = save_exception_stack;
	error_context_stack = save_context_stack;

	/* Release everything the test case allocated. */
	MemoryContextSwitchTo(FuzzContext);
	MemoryContextReset(FuzzContext);

	return 0;
}
