/*-------------------------------------------------------------------------
 *
 * fuzz_recv.c
 *	  A libFuzzer harness for exercising type "receive" (binary input)
 *	  functions of PostgreSQL data types, including those provided by
 *	  extensions such as contrib/ltree.
 *
 * A receive function has the signature
 *
 *		Datum typrecv(StringInfo buf [, Oid typioparam, int32 typmod])
 *
 * and turns the on-the-wire binary representation of a value into the
 * type's in-memory representation.  Because the bytes come straight from a
 * client, a buggy receive function is a memory-safety hazard: this harness
 * feeds fuzzer-generated bytes to a chosen receive function so that tools
 * such as AddressSanitizer/UndefinedBehaviorSanitizer can catch crashes,
 * buffer overreads and the like.
 *
 * The concrete function to fuzz is selected at compile time.  The build
 * system defines FUZZ_RECV_SYMBOL to the C name of the receive function and
 * links the object files that implement it (plus the whole backend, from
 * which the receive function resolves its dependencies).  See meson.build
 * and README for the list of ready-made targets and instructions for adding
 * new ones.
 *
 * The harness deliberately keeps the amount of backend state it initializes
 * to a minimum: just enough (memory contexts, error handling and the stack
 * depth reference point) for a self-contained receive function to run.  It
 * does *not* start a real backend, so it must only be used with receive
 * functions that do not require catalog access or a live transaction.  The
 * ltree/lquery/ltxtquery receive functions satisfy this requirement.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  src/test/fuzz/fuzz_recv.c
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include "fmgr.h"
#include "miscadmin.h"
#include "utils/memutils.h"

#ifndef FUZZ_RECV_SYMBOL
#error "define FUZZ_RECV_SYMBOL to the receive function to fuzz"
#endif

/*
 * The receive function under test.  It is compiled into this binary together
 * with the rest of its module; here we just declare it so we can take its
 * address.  All in-core and contrib receive functions have C linkage and the
 * standard PG_FUNCTION_ARGS signature.
 */
extern Datum FUZZ_RECV_SYMBOL(FunctionCallInfo fcinfo);

/*
 * libFuzzer entry points.  libFuzzer's runtime provides main(); it calls
 * LLVMFuzzerInitialize() once and LLVMFuzzerTestOneInput() for every test
 * case.  (The backend static library we link against also defines a main(),
 * so the executable is linked with --allow-multiple-definition, which keeps
 * libFuzzer's; see meson.build.)
 */
int			LLVMFuzzerInitialize(int *argc, char ***argv);
int			LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);

/* Long-lived context that owns everything allocated while fuzzing. */
static MemoryContext FuzzContext = NULL;

/*
 * LLVMFuzzerInitialize
 *
 * Called once by libFuzzer before the first test case.  Bring up the minimum
 * backend infrastructure the receive functions rely on.
 */
int
LLVMFuzzerInitialize(int *argc, char ***argv)
{
	/*
	 * Establish a reference point for stack-depth checking.  Several parsers
	 * reached from receive functions call check_stack_depth(); without a
	 * stack base they would compute a bogus depth.
	 */
	(void) set_stack_base();

	/* Set up the memory context subsystem (TopMemoryContext, ErrorContext). */
	MemoryContextInit();

	/*
	 * A dedicated context for everything a single test case allocates.  We
	 * reset it after every iteration so that memory usage stays bounded even
	 * across millions of inputs.
	 */
	FuzzContext = AllocSetContextCreate(TopMemoryContext,
										"FuzzContext",
										ALLOCSET_DEFAULT_SIZES);
	MemoryContextSwitchTo(FuzzContext);

	return 0;
}

/*
 * LLVMFuzzerTestOneInput
 *
 * Called once per test case with a fuzzer-generated byte string.  The bytes
 * are handed to the receive function as the body of a binary message.
 */
int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
	sigjmp_buf	local_sigjmp_buf;
	sigjmp_buf *save_exception_stack = PG_exception_stack;
	ErrorContextCallback *save_context_stack = error_context_stack;

	MemoryContextSwitchTo(FuzzContext);

	/*
	 * Emulate the backend's top-level error handling.  A malformed input is
	 * expected to raise an ordinary ereport(ERROR); we catch it, clean up and
	 * move on to the next test case.  A genuine memory-safety bug will instead
	 * trip a sanitizer or crash, which is exactly what we want the fuzzer to
	 * find.
	 */
	if (sigsetjmp(local_sigjmp_buf, 1) == 0)
	{
		StringInfoData buf;

		PG_exception_stack = &local_sigjmp_buf;

		/*
		 * Build a StringInfo owned by FuzzContext holding a private copy of
		 * the fuzzer input, so receive functions may freely advance the
		 * cursor and read the data without touching the caller's buffer.
		 */
		initStringInfo(&buf);
		appendBinaryStringInfo(&buf, (const char *) data, (int) size);

		/*
		 * Invoke the receive function.  DirectFunctionCall1 supplies the
		 * remaining (unused-by-us) fcinfo fields; typioparam and typmod
		 * default to InvalidOid/-1 which the targeted functions ignore.
		 */
		(void) DirectFunctionCall1(FUZZ_RECV_SYMBOL, PointerGetDatum(&buf));
	}
	else
	{
		/* Caught an ereport(ERROR): discard the error and continue. */
		PG_exception_stack = save_exception_stack;
		error_context_stack = save_context_stack;
		FlushErrorState();
	}

	PG_exception_stack = save_exception_stack;
	error_context_stack = save_context_stack;

	/* Release everything the test case allocated. */
	MemoryContextSwitchTo(FuzzContext);
	MemoryContextReset(FuzzContext);

	return 0;
}
